[2024-07-01T11:32:12.756-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T11:32:12.778-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_pipeline.extract_stock_data scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-07-01T11:32:12.785-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_pipeline.extract_stock_data scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-07-01T11:32:12.786-0400] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-07-01T11:32:12.795-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_stock_data> on 2024-06-04 00:00:00+00:00
[2024-07-01T11:32:12.809-0400] {logging_mixin.py:188} WARNING - /Users/christophercunningham/airflow_workspace/data-flow/data_flow_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=26205) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-01T11:32:12.810-0400] {standard_task_runner.py:63} INFO - Started process 26214 to run task
[2024-07-01T11:32:12.809-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_data_pipeline', 'extract_stock_data', 'scheduled__2024-06-04T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/af-dag__run_stock_data_pipeline.py', '--cfg-path', '/var/folders/d3/l1h2w3dj6m9cnl162jqdffzm0000gn/T/tmp4tah9u4i']
[2024-07-01T11:32:12.811-0400] {standard_task_runner.py:91} INFO - Job 29: Subtask extract_stock_data
[2024-07-01T11:32:12.857-0400] {task_command.py:426} INFO - Running <TaskInstance: stock_data_pipeline.extract_stock_data scheduled__2024-06-04T00:00:00+00:00 [running]> on host christophersmbp.lan
[2024-07-01T11:32:12.914-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ccunningham' AIRFLOW_CTX_DAG_ID='stock_data_pipeline' AIRFLOW_CTX_TASK_ID='extract_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-04T00:00:00+00:00'
[2024-07-01T11:32:12.916-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T11:32:12.917-0400] {data_extractor.py:14} INFO - Beginning data extraction for GME
[2024-07-01T11:33:18.262-0400] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-07-01T11:33:18.262-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-01T11:33:18.287-0400] {process_utils.py:132} INFO - Sending 15 to group 26214. PIDs of all processes in the group: [26214]
[2024-07-01T11:33:18.287-0400] {process_utils.py:87} INFO - Sending the signal 15 to group 26214
[2024-07-01T11:34:18.379-0400] {process_utils.py:150} WARNING - process psutil.Process(pid=26214, name='Python', status='running', started='11:32:12') did not respond to SIGTERM. Trying SIGKILL
[2024-07-01T11:34:18.381-0400] {process_utils.py:87} INFO - Sending the signal 9 to group 26214
[2024-07-01T11:34:18.388-0400] {process_utils.py:80} INFO - Process psutil.Process(pid=26214, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='11:32:12') (26214) terminated with exit code -9
[2024-07-01T11:34:18.389-0400] {standard_task_runner.py:178} ERROR - Job 29 was killed before it finished (likely due to running out of memory)
